# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1073741823, verbose_name='内容')),
                ('markdown_content', models.TextField(help_text='使用Markdown编辑器编写的内容', max_length=1073741823, verbose_name='Markdown内容')),
            ],
            options={
                'verbose_name_plural': '文档内容',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticleImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai/%Y-%m')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '文档图片',
                'db_table': 'article_img',
            },
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='标题')),
                ('description', models.CharField(max_length=2048, verbose_name='描述')),
                ('praise', models.BigIntegerField(default=0, verbose_name='赞')),
                ('visit', models.BigIntegerField(default=0, verbose_name='访问量')),
                ('tags', models.TextField(blank=True, help_text='多个标签用 "," 逗号分隔', max_length=1500, null=True, verbose_name='标签')),
                ('channel', models.IntegerField(blank=True, choices=[(1, '前端'), (2, '后端'), (3, '运维'), (4, '数据库'), (5, '其它')], help_text='对数据表中所有博客的分类', null=True, verbose_name='文档分类')),
                ('type', models.CharField(choices=[('original', '原'), ('repost', '转'), ('translated', '译')], default='original', max_length=16, verbose_name='文档类型')),
                ('is_private', models.BooleanField(default=False, verbose_name='是否私密')),
                ('is_draft', models.BooleanField(default=True, verbose_name='是否草稿')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('access_password', models.CharField(blank=True, help_text='为空，即无密码', max_length=32, null=True, verbose_name='访问密码')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
            ],
            options={
                'verbose_name_plural': '文档信息',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='分类名称')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '文档分类',
                'db_table': 'classify',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1073741823, verbose_name='评论内容')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='评论日期')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.BlogInfo', verbose_name='被评文档')),
                ('reply', models.ForeignKey(blank=True, help_text='自关联，为空即无回复', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='回复')),
            ],
            options={
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
    ]
